- repokid/filters/age/__init__.py
- repokid/repokid.py
- repokid/utils/roledata.py
- Order imports
- Display an error if Aardvark can't be accessed
- Handle problems manipulating policies better
- Fixing a bug where we shouldn't do anything if there are no repoable permissions
> Misc fixes

- repokid/repokid.py
- repokid/role.py
- repokid/utils/roledata.py
- test-requirements.txt
- tests/test_repokid.py
Some tests for update_role_cache and display_role_cache.  Left
to do are other functions in repokid, tests for repoable logic,
and tests for Dynamo.
> First crack at unit tests

- repokid/repokid.py
- repokid/role.py
- repokid/utils/roledata.py
- tests/test_repokid.py
This commit adds descriptions for all of the functions, cleans up
a few unrequired functions and bits, and otherwise generally
improves readability without changing functionality.
> Docstrings for every function, alpha order, and cleanup

- .gitignore
- .travis.yml
- repokid/__init__.py
- repokid/cli/repokid_cli.py
- repokid/exceptions/__init__.py
- repokid/filters/age/__init__.py
- repokid/filters/blacklist/__init__.py
- repokid/filters/lambda/__init__.py
- repokid/filters/optout/__init__.py
- repokid/role.py
- repokid/tests/test_repokid_cli.py
- repokid/tests/test_roledata.py
- repokid/utils/dynamo.py
- repokid/utils/roledata.py
- setup.py
Major commit to refactor lots of things:
- Remove globals - config and dynamo object are passed explicitly
where required
- Split Dynamo specific logic to a Dynamo utility and made it all
generic rather than specific Dynamo statements as functions
- Wrapper for Dynamo calls that will catch and log errors
- Lots of other stuff
> Total refactor

- repokid/utils/roledata.py
Add `organizations` to the frozenset so that repokid does not repo this service.
> Add organizations to the frozenset

- repokid/__init__.py
- repokid/cli/repokid_cli.py
- repokid/hooks/__init__.py
- repokid/hooks/loggers.py
- repokid/hooks/loggers/__init__.py
- repokid/tests/artifacts/hook/__init__.py
- repokid/tests/test_hooks.py
- repokid/tests/test_repokid_cli.py
- repokid/tests/test_roledata.py
- repokid/utils/roledata.py
- Added hooks ( Reference implementations )
-- During repoable calculations
-- after schedule repo
-- after repo
- Added a decorator to find define the function hooks
- Added a way to discover hooks
- Added config for the hooks
- Added testcases
> Implemented hooks to repokid

- .travis.yml
- setup.cfg
- test-requirements.txt
> add flake8 to travis ci

- README.md
This commit updates the documentation to correctly reflect the
required tables and attributes.
fixes #58
> Updating documentation to reflect newly required tables and attrs

- repokid/cli/repokid_cli.py
This commit adds two commands - list scheduled repos and cancel
scheduled repo for a given role.
> Adding view scheduled and cancel scheduled

- README.md
Simple one, just adding the Travis CI badge to the repo.
> UPDATE readme.md with travis ci badge to display status

- repokid/__init__.py
- repokid/cli/repokid_cli.py
As per Gitter chat, surface this information as well inside `repo_stats` output
> Add Active field to repo_stats command

- repokid/utils/roledata.py
Update since Access Advisor supports aws tagging service now
> Update since Access Advisor supports aws tagging service now

- repokid/__init__.py
- repokid/role.py
- repokid/utils/dynamo.py
- repokid/utils/roledata.py
- requirements.txt
This commit modifies Repokid so that tags are now stored. Repokid becoming tag aware enables us to filter based on tag values.
> Support tags for filtering

- .flake8
- repokid/cli/dispatcher_cli.py
- repokid/cli/repokid_cli.py
- repokid/dispatcher/__init__.py
- repokid/filters/age/__init__.py
- repokid/filters/blacklist/__init__.py
- repokid/tests/test_dispatcher_cli.py
- repokid/tests/test_hooks.py
- repokid/tests/test_repokid_cli.py
- repokid/tests/test_roledata.py
- repokid/utils/dynamo.py
- repokid/utils/roledata.py
- setup.py
- test-requirements.txt
Fix all the flake8 import order findings and include the plugin that checks them.
> Fix flake8 import orders

- Dockerfile
Updates the Dockerfile to use the official Python 3.7 container. This resolves the Python dependency issues that were related to the use of Python 2.7 with Python 3 packages.
> Update Dockerfile to use Python 3.7. Resolves python dependency issues.

- .travis.yml
- repokid/__init__.py
Add PyPI package upload on tags on `master` branch.
> Add PyPI upload to CI

- MANIFEST.in
- repokid/__init__.py
- setup.py
- Add long description
- Add `requirements.in` to manifest
> Fix PyPI distribution

- README.md
Add documentation about available hooks to the README.
> Add hook documentation to readme

- repokid/__init__.py
> Support loading Repokid configuration specified from env var

- repokid/role.py
Tag updates got lost in the refactoring. This PR fixes that.
> Fix tag updates in Role.gather_role_data()

- repokid/commands/repo.py
- repokid/commands/schedule.py
- repokid/dispatcher/__init__.py
- repokid/exceptions.py
- repokid/role.py
- repokid/utils/dynamo.py
- requirements-test.txt
- requirements.txt
- tests/test_role.py
This PR adds more graceful handling of DynamoDB failures, including a workaround for max item sizes. I also upgraded requirements and did some other housekeeping.
> Improve how the role model handles DynamoDB failures
