Netflix/repokid

repokid/filters/blacklist/__init__.py
repokid/filters/lambda/__init__.py
repokid/repokid.py

This commit moves logging of applied filters out of the filters
themselves.  Plugins that want additional logging (like age
details) can still log, but an info level event will occur each
time a role is filtered by a plugin.

Add central logging for filters

---

repokid/repokid.py

This commit fixes a simple bug in time format.  We are actually
reading abbreviated month, not full month name.

Fixing a bug in the timestamp checking from Aardvark

---

repokid/utils/roledata.py

This commit makes the assume role for Dynamo optional.  If not
specified in config it will not attempt to assume a role.

Making assume role optional for Dynamo

---

repokid/filters/age/__init__.py
repokid/filters/blacklist/__init__.py
repokid/filters/lambda/__init__.py
repokid/repokid.py
repokid/role.py
repokid/utils/roledata.py

This (large) commit refacts Repokid to use a class instead of
passing dict values around everywhere.  We also now use local
copies of data whenever possible instead of retrieving from
Dynamo.  When we do retrieve from Dynamo we retrieve the smallest
amount of data possible.

Change Role to be a class and performance improvements

---

repokid/repokid.py

LightSail doesn't seem to be supported by access advisor.  Instructing repokid to act accordingly.

Adding lightsail to unsupported Access Advisor services

---

repokid/repokid.py

This commit fixes a bug where config generation tries to log with
a logger that doesn't exist yet.  Instead we'll print.

Fixing a bug with logging when generating config

---

repokid/repokid.py
tests/test_repokid.py

This commit fixes two bugs.  The first bug would prevent roles
which had been previously filtered from becoming unfiltered.  By
being too eager to save Dynamo operations we were updating only
roles with filters, which had the unfortunate side effect that
roles can't become unfiltered.
The other bug was attempting to use a exception details in an
error that wasn't triggered by an exception.

Two bug fixes

---

repokid/repokid.py
repokid/role.py
repokid/utils/roledata.py
tests/test_repokid.py

This commit adds a new feature that detects newly added
permissions and adds them to a list.  The temporary block period
is configurable.  When permissions are scanned any that are new
from the last policy version are added to 'NoRepoPermissions'.
Expired entries are removed during update, but any that are
expired will be ignored from _get_repoable_permissions.
Also fix a bug where sometimes when adding a new policy the
new policy version wouldn't get added at the right place.

Adding a way to block newly added permissions from repo

---

repokid/__init__.py
repokid/filters/optout/__init__.py
repokid/repokid.py
repokid/role.py
repokid/utils/roledata.py
setup.py
tests/test_repokid.py
tests/test_roledata.py

This commit adds an opt-out field, which will be used by the upcoming repokid_reactor.  Also move everything that is commonly used to utils/roledata so that repokid CLI is not required to load common utils.

Add an opt-out field and refactor common stuff to a library so it can be used by upcoming repokid_reactor

---

repokid/cli/repokid_cli.py
repokid/tests/test_repokid_cli.py
repokid/utils/dynamo.py
repokid/utils/roledata.py

Performance improvemetns in a few cases - we don't load all the
data for a role we're repoing unless we need to.
Warnings are suppressed for unknown permissions by default but
can be enabled in config.

Make a few small tweaks

---

README.md
repokid/__init__.py
repokid/cli/repokid_cli.py
repokid/filters/optout/__init__.py
repokid/tests/test_roledata.py
repokid/utils/dynamo.py
repokid/utils/roledata.py

- Create a new function that can update individual role data.
This is useful so we can get an accurate count of repoable, etc
permissions after a repo or rollback.
- Find roles by name using a secondary index now (should improve
performance significantly)
- Change description when a role is repoed to include the date
- When showing warnings about a permission being on the no repo
list, show info instead and show the role name
- Only update stats when the count or repoable services are
different than before
- Fix a bug where display role fails if a bad role name is given
- Fix a bug in the OptOut filter

A few enhancements

---

repokid/cli/repokid_cli.py
repokid/tests/test_repokid_cli.py
repokid/utils/roledata.py

This commit fixes a bug in opt-out filter caused by failing
to get the current opt-out status from the Dynamo table.  Now, as
part of getting an existing role we'll update all data from
Dynamo.
Also force an update_role_cache prior to repo_all_roles as a
safety mechanism.

Fix a bug in opt-out filter

---

repokid/__init__.py
repokid/cli/repokid_cli.py
repokid/utils/dynamo.py
repokid/utils/roledata.py

The find_role_in_cache function had a bug that would return the
wrong role if multiple existed across accounts because it wasn't
checking the account number matched.

Fixing a bug with same role name in multiple accounts

---

repokid/utils/dynamo.py

This commit adds a empty string substitution when adding
items to the end of a list to fix a bug observed while adding
a new policy version with an empty string.

Fix a bug on adding to a list

---

.gitignore
repokid/utils/roledata.py

This commit fixes a bug where Disqualified By might not be set yet (it's not a field that's returned from new roles, so it doesn't yet exist in the table).
Fixes #60

Fix bug on first run

---

repokid/__init__.py
repokid/cli/repokid_cli.py
repokid/dispatcher/__init__.py
repokid/tests/test_roledata.py
repokid/utils/roledata.py

This commit changes repoable permissions to allow storing repoable
permissions too.  Access Advisor only gives information for the
whole service level, so Repokid was designed to store a list of
repoable services.  Now with additional data sources we might have
individual permissions being repoed too so we can store these in
the list.  To support this we've created two new utility
functions:
- convert repoable permissions list to services and permissions
- split the repoable service back to perms and services list

Allow permissions to be listed in repoable services too

---

repokid/__init__.py
repokid/cli/repokid_cli.py
repokid/utils/roledata.py

Hello Repokid developers 👋,
I'm sending this PR to write the repoable permissions count in the `repo_stats` command output as I find this information quite useful to track in our daily stats runs, I hope you'll find this useful as well 🙂
Cheers,
Marco
PS: repokid rocks! thanks for open sourcing it

Add repoable permissions count to stats

---

repokid/__init__.py
repokid/cli/repokid_cli.py
repokid/dispatcher/__init__.py

This commit fixes the rollback function of the dispatcher.  This
was broken because when we added hooks everywhere we made it a
required parameter for rollback.  To fix this we move the
_get_hooks function to the module level and call it from the
dispatcher.

Fix dispatcher rollback

---

repokid/__init__.py
repokid/cli/repokid_cli.py

My current workflow is, for each day:
- `update_role_cache`
- `schedule_repo`
- `repo_scheduled_roles -c`
I'm using the default 7 days grace period for scheduled roles. While running `show_scheduled_roles` I noticed that the Scheduled time entry was getting updated after each run of schedule_repo, thus postponing the repoing every day.
This PR introduces an extra check that does not update the Scheduled entry if already set.

Do not reschedule already scheduled roles

---

README.md
repokid/__init__.py
repokid/utils/dynamo.py

This PR uses `resource.tables.all()` to lookup Repokid DynamoDB table instead of attempting to create such table every time and catch `ResourceInUseException` if it's already there.
Adds `dynamodb:ListTables` as requirement for RepokidInstanceProfile. Is it OK?

Lookup repokid_roles table instead of using ResourceInUseException

---

README.md
repokid/__init__.py
repokid/cli/repokid_cli.py
repokid/dispatcher/__init__.py
repokid/tests/test_repokid_cli.py
repokid/tests/test_roledata.py
repokid/utils/dynamo.py
repokid/utils/roledata.py
requirements.txt
setup.py
test-requirements.txt

These commits move Repokid to using iam:GetAccountAuthorizationDetails instead of the list-roles and get-role-inline-policies calls while updating the role cache. This is a big performance improvement and updating is much faster.
While at it, fix all the flake8 complaints.

Get-account-auth-details and misc flake8 fixes

---

repokid/__init__.py
repokid/cli/repokid_cli.py
repokid/role.py
repokid/tests/test_repokid_cli.py
repokid/tests/test_roledata.py
repokid/utils/roledata.py

This commit changes scheduled repoing to track which permissions
were scheduled. This is needed because we only want to take away
permissions we have told the developers about.
With this change, if you schedule a repo it will keep an entry in
Dynamo with the current repoable permissions and services.
Repoing these scheduled roles will only remove permissions that
are in this scheduled set.
This commit also adds the ability to cancel a scheduled repo
for every role in the account.

Track scheduled repo permissions

---

repokid/__init__.py
repokid/cli/repokid_cli.py
repokid/hooks/loggers/__init__.py
repokid/tests/test_repokid_cli.py

This commit adds a hook that fires before repoing all roles
(scheduled or not). This gives the chance to do filtering based
on account number or roles in the list.

Adding a hook for before repo roles

---

README.md
repokid/cli/repokid_cli.py
repokid/tests/test_repokid_cli.py

Adding _remove_permissions_from_roles() and extracting parts of repo_role() into shared methods.
Also updates the policy size checking to correctly remove all whitespace before checking the size.
Need a code review with @mcpeak.

Adding _remove_permissions_from_roles() and extracting parts of repo_role() into shared methods.

---

repokid/__init__.py
repokid/cli/repokid_cli.py

This commit removes roles that show as scheduled when they should
not by:
1) Only showing active roles in show_scheduled_roles
2) If repoing encounters a problem, unschedule the role

Fixes to scheduled roles

---

repokid/cli/repokid_cli.py
repokid/dispatcher/__init__.py
repokid/tests/test_roledata.py
repokid/utils/roledata.py
requirements.txt

repokid will now ignore statements with an Sid beginning with NOREPO.
repokid will also no longer expand wildcards on statements that don't have any repoable permissions.
`roledata.py::_get_repoed_policy()` will no longer try to repo statements with Sid's beginning with NOREPO.
`roledata.py::_get_permissions_in_policy()` now has two return values:
1) total_permissions
2) eligible_permissions <-- This is a subset of total, but excludes permissions in statements with the NOREPO Sid.
New tests should cover the logic pretty well.
Bumping version of policyuniverse

Skip statements with Sid beginning NOREPO

---

repokid/__init__.py
repokid/cli/repokid_cli.py
repokid/commands/repo.py
repokid/commands/role.py
repokid/commands/role_cache.py
repokid/commands/schedule.py
repokid/filters/__init__.py
repokid/filters/age/__init__.py
repokid/filters/blocklist/__init__.py
repokid/filters/exclusive/__init__.py
repokid/hooks/loggers/__init__.py
repokid/utils/aardvark.py
repokid/utils/dynamo.py
repokid/utils/iam.py
repokid/utils/logging.py
repokid/utils/roledata.py

LOGGER was being imported from repokid module but it was not able to
find the module variable.
As a quick workaround I assigned (per Patrick Sanders' recommendation)
LOGGER directly to logging.getLogger("repokid") and import logging
module where needed.

Assign LOGGER instead of importing

---

repokid/__init__.py
repokid/exceptions/__init__.py
repokid/filters/blocklist/__init__.py
repokid/utils/aardvark.py
repokid/utils/dynamo.py

This PR:
- replaces calls to `sys.exit()` with exceptions to be handled at higher levels
- makes the blocklist a class variable so it only needs to be fetched from S3 once per run

Don't exit on errors, only fetch blocklist once

---

AUTHORS
repokid/__init__.py
repokid/commands/repo.py
repokid/lib/__init__.py
repokid/utils/dynamo.py

Add `update` flag to allow library calls to skip the update_role_cache
call when repoing one or more roles with a default of `True`.

Add update flag to repo methods

---

README.md
repokid/__init__.py
repokid/commands/repo.py
repokid/lib/__init__.py
repokid/tests/test_commands.py

Allow users to specify a `limit` that will limit how many roles are
repoed at one time. This is an optional kwarg that defaults to a value
of zero, which results in not limiting the repo action.
Also add `AFTER_REPO_ROLES` hook and add `errors` to the
`AFTER_REPO` hooks context.

Add `limit` kwarg to repo functions

---

README.md
repokid/commands/repo.py
repokid/commands/role.py
repokid/commands/role_cache.py
repokid/commands/schedule.py
repokid/role.py
repokid/tests/test_commands.py
repokid/tests/test_hooks.py
repokid/tests/test_roledata.py
repokid/utils/roledata.py
requirements.in
requirements.txt
setup.py

- Refactor Role model to use Pydantic
- Call `Role.parse_obj()` to instantiate roles from dicts
- Refactor `update_role_data()` to not mutate role object, but instead return an updated instance
- Send `role_id` to `DURING_REPOABLE_CALCULATION` hook
- Update tests for all of the above

Refactor Role model to use Pydantic

---

repokid/commands/role_cache.py
repokid/exceptions.py
repokid/role.py
repokid/tests/conftest.py
repokid/tests/test_commands.py
repokid/tests/test_hooks.py
repokid/tests/test_role.py
repokid/tests/test_roledata.py
repokid/tests/vars.py
repokid/utils/dynamo.py
repokid/utils/dynamo_v2.py
repokid/utils/roledata.py
requirements-test.txt
requirements.txt

This PR refactors the role model so the logic for data retrieval and persistence is more self-contained. There will be a follow-up to use these new methods throughout the codebase.

Add persistence methods to Role model

---

repokid/commands/role_cache.py
repokid/datasource/access_advisor.py
repokid/datasource/iam.py
repokid/datasource/plugin.py

This fixes a bug where running `update_role_cache()` on multiple accounts would end up duplicating work and potentially causing problems.

Return IDs of items seeded into datasources

---

repokid/commands/schedule.py
repokid/role.py
tests/test_commands.py

This PR helps ensure Role objects have Access Advisor data during the scheduling process.

Add flag to fetch AA data on Role fetch

---

.gitignore
repokid/commands/repo.py
repokid/commands/role.py
repokid/commands/role_cache.py
repokid/datasource/access_advisor.py
repokid/datasource/iam.py
repokid/datasource/plugin.py
repokid/plugin.py
repokid/role.py
repokid/utils/dynamo.py
repokid/utils/iam.py
repokid/utils/permissions.py
tests/datasource/test_iam.py
tests/test_commands.py
tests/test_role.py

This PR moves more logic into the Role model and out of the `commands` module.
Additional changes/improvements:
- Switch datasource singletons to a metaclass instead of multiple inheritance
- Fix an inconsistency in determining which actions could be removed, resulting in too few being eligible

Refactor: Consolidate more logic into Role model

---

README.md
repokid/commands/repo.py
repokid/commands/role.py
repokid/commands/role_cache.py
repokid/datasource/iam.py
repokid/role.py
repokid/utils/dynamo.py
repokid/utils/permissions.py
tests/datasource/test_iam.py
tests/test_commands.py
tests/test_permissions.py.bak
tests/test_role.py

Switch to using ARNs as the primary key instead of RoleId. This makes it easier to interact with RepoKid on an ad hoc basis.
Some things to note:
* The IAM datasource can be used without seeding (yay!). This was a big motivator for this change. The datasource will fall back to an IAM get_role call instead of requiring the get_account_authorization_details call for every run. You should still seed the datasource if you're interacting with more than a handful of roles in an account.
* Role instantiation makes some assumptions about conversions between ARN and account/role name. This can be found in `Role.derive_from_arn()`.
* `DURING_REPOABLE_CALCULATION` hooks now get `arn` in their input dict.
* ⚠️ A new DynamoDB index is added to support keying off of ARNs. This prompted a bit of …

Use ARN as key for role handling

---

repokid/filters/age/__init__.py
tests/filters/__init__.py
tests/filters/test_age.py

This PR fixes an error resulting from an offset-aware `create_date` in a Role object being compared to an offset-naive datetime in the Age filter. I also added tests to reproduce and then validate the fix.
Fixes #284

Ensure offset-naive datetime in age filter

---

repokid/cli/repokid_cli.py
requirements.in

* Pin `boto3-stubs` to `<=1.17.71` to avoid vemel/mypy_boto3_builder#75.
* Fix Click imports to resolve mypy failures with click 8.0.0
Fixes #287

Pin boto3-stubs version, fix Click imports

---

repokid/utils/dynamo.py

This PR fixes a bug in which the active check on a role would always evaluate to `True` if any value was present (e.g. `"false"` or `"potatoes"`), thus returning the first item in the query results.

Fix active check when multiple results found in DDB
